routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PaiseController;
use App\Http\Controllers\EstadoController;
use App\Http\Controllers\CiudadeController;
use App\Http\Controllers\UsuarioController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(["register" => false]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

//Creamos un grupo de rutas protegidas
Route::group(['middleware' => ['auth']], function () {
    Route::get('/', function () {
        return view('home');
    });
    Route::resource('usuarios', UsuarioController::class);
    Route::resource('paises', PaiseController::class);
    Route::resource('estados', EstadoController::class);
    Route::resource('ciudades', CiudadeController::class);

    Route::get('obtener_estados', [UsuarioController::class, 'obtener_estados'])->name('obtener.estados');
    Route::get('obtener_ciudades', [UsuarioController::class, 'obtener_ciudades'])->name('obtener.ciudades');

    Route::get('/crearcorreo', function () {
        return view('correo.formulario');
    })->name('crearcorreo');
    
    Route::post('/enviarcorreo', [App\Http\Controllers\EmailController::class, 'enviarcorreo'])->name('enviarcorreo');


});

app/Models/Paise.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Paise
 *
 * @property $id
 * @property $paise
 * @property $created_at
 * @property $updated_at
 *
 * @property Estado[] $estados
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Paise extends Model
{
    
    static $rules = [
		'paise' => 'required',
    ];

    protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['paise'];


    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function estados()
    {
        return $this->hasMany('App\Models\Estado', 'paise_id', 'id');
    }
    

}

app/Http/Controllers/PaiseController.php
<?php

namespace App\Http\Controllers;

use App\Models\Paise;
use Illuminate\Http\Request;

/**
 * Class PaiseController
 * @package App\Http\Controllers
 */
class PaiseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $paises = Paise::paginate();

        return view('paise.index', compact('paises'))
            ->with('i', (request()->input('page', 1) - 1) * $paises->perPage());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $paise = new Paise();
        return view('paise.create', compact('paise'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate(Paise::$rules);

        $paise = Paise::create($request->all());

        return redirect()->route('paises.index')
            ->with('success', 'Paise created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $paise = Paise::find($id);

        return view('paise.show', compact('paise'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $paise = Paise::find($id);

        return view('paise.edit', compact('paise'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Paise $paise
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Paise $paise)
    {
        request()->validate(Paise::$rules);

        $paise->update($request->all());

        return redirect()->route('paises.index')
            ->with('success', 'Paise updated successfully');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $paise = Paise::find($id)->delete();

        return redirect()->route('paises.index')
            ->with('success', 'Paise deleted successfully');
    }
}

resources/views/paise/create.blade.php
@extends('layouts.app')

@section('template_title')
    {{ __('Create') }} Paise
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">{{ __('Create') }} Paise</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('paises.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('paise.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/paise/edit.blade.php
@extends('layouts.app')

@section('template_title')
    {{ __('Update') }} Paise
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">{{ __('Update') }} Paise</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('paises.update', $paise->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('paise.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/paise/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">
        
        <div class="form-group">
            {{ Form::label('paise') }}
            {{ Form::text('paise', $paise->paise, ['class' => 'form-control' . ($errors->has('paise') ? ' is-invalid' : ''), 'placeholder' => 'Paise']) }}
            {!! $errors->first('paise', '<div class="invalid-feedback">:message</div>') !!}
        </div>

    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">{{ __('Submit') }}</button>
    </div>
</div>

resources/views/paise/index.blade.php
@extends('layouts.app')

@section('template_title')
    Paise
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div style="display: flex; justify-content: space-between; align-items: center;">

                            <span id="card_title">
                                {{ __('Paise') }}
                            </span>

                             <div class="float-right">
                                <a href="{{ route('paises.create') }}" class="btn btn-primary btn-sm float-right"  data-placement="left">
                                  {{ __('Create New') }}
                                </a>
                              </div>
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover">
                                <thead class="thead">
                                    <tr>
                                        <th>No</th>
                                        
										<th>Paise</th>

                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($paises as $paise)
                                        <tr>
                                            <td>{{ ++$i }}</td>
                                            
											<td>{{ $paise->paise }}</td>

                                            <td>
                                                <form action="{{ route('paises.destroy',$paise->id) }}" method="POST">
                                                    <a class="btn btn-sm btn-primary " href="{{ route('paises.show',$paise->id) }}"><i class="fa fa-fw fa-eye"></i> {{ __('Show') }}</a>
                                                    <a class="btn btn-sm btn-success" href="{{ route('paises.edit',$paise->id) }}"><i class="fa fa-fw fa-edit"></i> {{ __('Edit') }}</a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i> {{ __('Delete') }}</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {!! $paises->links() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/paise/show.blade.php
@extends('layouts.app')

@section('template_title')
    {{ $paise->name ?? "{{ __('Show') Paise" }}
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title">{{ __('Show') }} Paise</span>
                        </div>
                        <div class="float-right">
                            <a class="btn btn-primary" href="{{ route('paises.index') }}"> {{ __('Back') }}</a>
                        </div>
                    </div>

                    <div class="card-body">
                        
                        <div class="form-group">
                            <strong>Paise:</strong>
                            {{ $paise->paise }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection