routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PaiseController;
use App\Http\Controllers\EstadoController;
use App\Http\Controllers\CiudadeController;
use App\Http\Controllers\UsuarioController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(["register" => false]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

//Creamos un grupo de rutas protegidas
Route::group(['middleware' => ['auth']], function () {
    Route::get('/', function () {
        return view('home');
    });
    Route::resource('usuarios', UsuarioController::class);
    Route::resource('paises', PaiseController::class);
    Route::resource('estados', EstadoController::class);
    Route::resource('ciudades', CiudadeController::class);

    Route::get('obtener_estados', [UsuarioController::class, 'obtener_estados'])->name('obtener.estados');
    Route::get('obtener_ciudades', [UsuarioController::class, 'obtener_ciudades'])->name('obtener.ciudades');

    Route::get('/crearcorreo', function () {
        return view('correo.formulario');
    })->name('crearcorreo');
    
    Route::post('/enviarcorreo', [App\Http\Controllers\EmailController::class, 'enviarcorreo'])->name('enviarcorreo');


});

app/Http/Controllers/UsuarioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\Paise;
use App\Models\Estado;
use App\Models\Ciudade;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Arr;
use Illuminate\Validation\Rules\Password;

class UsuarioController extends Controller
{
    function __construct()
    {
        $this->middleware('permission:ver-usuario|crear-usuario|editar-usuario|borrar-usuario', ['only' => ['index']]);
        $this->middleware('permission:crear-usuario', ['only' => ['create', 'store']]);
        $this->middleware('permission:editar-usuario', ['only' => ['edit', 'update']]);
        $this->middleware('permission:borrar-usuario', ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $usuarios = User::all();
        return view('usuarios.index', compact('usuarios'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $paises = Paise::pluck('paise', 'id');
        return view('usuarios.crear', compact('paises'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd($request->fecha_nac);
        $this->validate($request, [
            'name' => 'required|max:100',
            'email' => 'required|email|unique:users,email',
            'fecha_nac' => 'required|before_or_equal:' . \Carbon\Carbon::now()->subYears(18)->format('Y-m-d'),
            'password' => ['required', 'same:confirm-password', Password::min(8)->mixedCase()->numbers()->symbols()],
            'telefono' => 'max:10',
            'cedula' => 'required|max:11',
            'ciudade_id' => 'required'
        ], [
            'fecha_nac.before_or_equal' => 'El usuario debe ser mayor de 18 años',
        ]);

        $input = $request->all();
        $input['password'] = Hash::make($input['password']);

        $user = User::create($input);

        return redirect()->route('usuarios.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        $paises = Paise::pluck('paise', 'id');

        return view('usuarios.editar', compact('user', 'paises'));
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (!empty($request->password)) {
            $this->validate($request, [
                'name' => 'required|max:100',
                'fecha_nac' => 'required|before_or_equal:' . \Carbon\Carbon::now()->subYears(18)->format('Y-m-d'),
                'password' => ['required', 'same:confirm-password', Password::min(8)->mixedCase()->numbers()->symbols()],
                'telefono' => 'max:10',
                'ciudade_id' => 'required'
            ], [
                'fecha_nac.before_or_equal' => 'El usuario debe ser mayor de 18 años',
            ]);
        } else {
            $this->validate($request, [
                'name' => 'required|max:100',
                'fecha_nac' => 'required|before_or_equal:' . \Carbon\Carbon::now()->subYears(18)->format('Y-m-d'),
                'telefono' => 'max:10',
                'ciudade_id' => 'required'
            ], [
                'fecha_nac.before_or_equal' => 'El usuario debe ser mayor de 18 años',
            ]);
        }

        $input = $request->all();
        if (!empty($input['password'])) {
            $input['password'] = Hash::make($input['password']);
        } else {
            $input = Arr::except($input, array('password'));
        }

        $user = User::find($id);
        $user->update($input);

        return redirect()->route('usuarios.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::find($id)->delete();
        return redirect()->route('usuarios.index');
    }

    public function obtener_estados(Request $request)
    {
        $estados = Estado::where('paise_id', $request->paise_id)->get();
        return response()->json($estados);
    }
    public function obtener_ciudades(Request $request)
    {
        $ciudades = Ciudade::where('estado_id', $request->estado_id)->get();
        return response()->json($ciudades);
    }
}

resources/views/usuarios/crear.blade.php
@extends('layouts.app')

@section('content')
    <section class="section">
        <div class="section-header">
            <h3 class="page__heading">Alta de Usuarios</h3>
        </div>
        <div class="section-body">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">

                            @if ($errors->any())
                                <div class="alert alert-dark alert-dismissible fade show" role="alert">
                                    <strong>¡Revise los campos!</strong>
                                    @foreach ($errors->all() as $error)
                                        <span class="badge badge-danger">{{ $error }}</span>
                                    @endforeach
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            @endif

                            {!! Form::open(['route' => 'usuarios.store', 'method' => 'POST']) !!}
                            <div class="row">
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label for="name">Nombre</label>
                                        {!! Form::text('name', null, ['class' => 'form-control']) !!}
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label for="email">E-mail</label>
                                        {!! Form::text('email', null, ['class' => 'form-control']) !!}
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label for="password">Password</label>
                                        {!! Form::password('password', ['class' => 'form-control']) !!}
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label for="confirm-password">Confirmar Password</label>
                                        {!! Form::password('confirm-password', ['class' => 'form-control']) !!}
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label for="telefono">Número Celular</label>
                                        {!! Form::number('telefono', null, ['class' => 'form-control']) !!}
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label for="cedula">Cédula</label>
                                        {!! Form::text('cedula', null, ['class' => 'form-control']) !!}
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label for="fecha_nac">Fecha Nacimiento</label>
                                        {!! Form::date('fecha_nac', null, ['class' => 'form-control']) !!}
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label for="paise_id">Pais</label>
                                        {{ Form::select('paise_id', $paises, null, ['id' => 'paise_id', 'class' => 'form-control', 'placeholder' => 'Selecciona un país']) }}
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label for="estado_id">Estado</label>
                                        {{ Form::select('estado_id', [], null, ['id' => 'estado_id', 'class' => 'form-control', 'placeholder' => 'Selecciona un estado']) }}
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label for="ciudade_id">Ciudad</label>
                                        {{ Form::select('ciudade_id', [], null, ['id' => 'ciudade_id', 'class' => 'form-control', 'placeholder' => 'Selecciona una ciudad']) }}
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <button type="submit" class="btn btn-primary">Guardar</button>
                                </div>
                            </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
@section('scripts')
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function() {
            //asignamos los select a variables
            var selectPaises = $('#paise_id');
            var selectEstados = $('#estado_id');
            var selectCiudades = $('#ciudade_id');

            //funcion para llenar select de estados cuando se cambie de opcion en el select de paises
            selectPaises.change(function() {
                var paise_id = $(this).val();
                selectEstados.empty();
                selectCiudades.empty();
                $.ajax({
                    url: "{{ route('obtener.estados') }}",
                    type: 'get',
                    data: {
                        paise_id: paise_id
                    },
                    dataType: 'json',
                    success: function(response) {
                        selectEstados.append('<option value="">Selecciona un estado</option>')
                        selectCiudades.append('<option value="">Selecciona una ciudad</option>')
                        $.each(response, function(key) {
                            selectEstados.append("<option value='" + response[key].id +
                                "'>" + response[key].estado + "</option>");
                        });
                    },
                    error: function() {
                        alert(
                            'Hubo un error obteniendo los estados. Contacte al administrador.'
                            );
                    }
                });
            });

            //funcion para llenar select de estados cuando se cambie de opcion en el select de paises
            selectEstados.change(function() {
                var estado_id = $(this).val();
                selectCiudades.empty();
                $.ajax({
                    url: "{{ route('obtener.ciudades') }}",
                    type: 'get',
                    data: {
                        estado_id: estado_id
                    },
                    dataType: 'json',
                    success: function(response) {
                        console.log(response);
                        selectCiudades.append('<option value="">Selecciona una ciudad</option>')
                        $.each(response, function(key) {
                            selectCiudades.append("<option value='" + response[key].id +
                                "'>" + response[key].ciudade + "</option>");
                        });
                    },
                    error: function() {
                        alert(
                            'Hubo un error obteniendo los estados. Contacte al administrador.'
                            );
                    }
                });
            });

        });
    </script>
@endsection

resources/views/usuarios/editar.blade.php
@extends('layouts.app')

@section('content')
    <section class="section">
        <div class="section-header">
            <h3 class="page__heading">Editar Usuario</h3>
        </div>
        <div class="section-body">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">

                            @if ($errors->any())
                                <div class="alert alert-dark alert-dismissible fade show" role="alert">
                                    <strong>¡Revise los campos!</strong>
                                    @foreach ($errors->all() as $error)
                                        <span class="badge badge-danger">{{ $error }}</span>
                                    @endforeach
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            @endif

                            <div class="row">
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <p><b>E-mail:</b> {{ $user->email }}</p>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <p><b>Cédula:</b> {{ $user->cedula }}</p>
                                    </div>
                                </div>
                            </div>

                            {!! Form::model($user, ['method' => 'PATCH', 'route' => ['usuarios.update', $user->id]]) !!}
                            <div class="row">
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label for="name">Nombre</label>
                                        {!! Form::text('name', null, ['class' => 'form-control']) !!}
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label for="password">Password</label>
                                        {!! Form::password('password', ['class' => 'form-control']) !!}
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label for="confirm-password">Confirmar Password</label>
                                        {!! Form::password('confirm-password', ['class' => 'form-control']) !!}
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label for="telefono">Número Celular</label>
                                        {!! Form::number('telefono', null, ['class' => 'form-control']) !!}
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label for="fecha_nac">Fecha Nacimiento</label>
                                        {!! Form::date('fecha_nac', null, ['class' => 'form-control']) !!}
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label for="paise_id">Pais</label>
                                        {{ Form::select('paise_id', $paises, null, ['id' => 'paise_id', 'class' => 'form-control', 'placeholder' => 'Selecciona un país']) }}
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label for="estado_id">Estado</label>
                                        {{ Form::select('estado_id', [], null, ['id' => 'estado_id', 'class' => 'form-control', 'placeholder' => 'Selecciona un estado']) }}
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <label for="ciudade_id">Ciudad</label>
                                        {{ Form::select('ciudade_id', [$user->ciudade->id => $user->ciudade->ciudade], null, ['id' => 'ciudade_id', 'class' => 'form-control', 'placeholder' => 'Selecciona una ciudad']) }}
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <button type="submit" class="btn btn-primary">Guardar</button>
                                </div>
                            </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
@section('scripts')
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function() {
            //asignamos los select a variables
            var selectPaises = $('#paise_id');
            var selectEstados = $('#estado_id');
            var selectCiudades = $('#ciudade_id');

            //funcion para llenar select de estados cuando se cambie de opcion en el select de paises
            selectPaises.change(function() {
                var paise_id = $(this).val();
                selectEstados.empty();
                selectCiudades.empty();
                $.ajax({
                    url: "{{ route('obtener.estados') }}",
                    type: 'get',
                    data: {
                        paise_id: paise_id
                    },
                    dataType: 'json',
                    success: function(response) {
                        selectEstados.append('<option value="">Selecciona un estado</option>')
                        selectCiudades.append('<option value="">Selecciona una ciudad</option>')
                        $.each(response, function(key) {
                            selectEstados.append("<option value='" + response[key].id +
                                "'>" + response[key].estado + "</option>");
                        });
                    },
                    error: function() {
                        alert(
                            'Hubo un error obteniendo los estados. Contacte al administrador.'
                        );
                    }
                });
            });

            //funcion para llenar select de estados cuando se cambie de opcion en el select de paises
            selectEstados.change(function() {
                var estado_id = $(this).val();
                selectCiudades.empty();
                $.ajax({
                    url: "{{ route('obtener.ciudades') }}",
                    type: 'get',
                    data: {
                        estado_id: estado_id
                    },
                    dataType: 'json',
                    success: function(response) {
                        console.log(response);
                        selectCiudades.append('<option value="">Selecciona una ciudad</option>')
                        $.each(response, function(key) {
                            selectCiudades.append("<option value='" + response[key].id +
                                "'>" + response[key].ciudade + "</option>");
                        });
                    },
                    error: function() {
                        alert(
                            'Hubo un error obteniendo los estados. Contacte al administrador.'
                        );
                    }
                });
            });

        });
    </script>
@endsection

resources/views/usuarios/index.blade.php
@extends('layouts.app')
@section('template_title')
    Usuarios
@endsection
@section('css')
    <link rel="stylesheet" href="http://cdn.datatables.net/1.13.4/css/jquery.dataTables.css" />
@endsection
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div style="display: flex; justify-content: space-between; align-items: center;">

                            <span id="card_title">
                                {{ __('Listado de usuarios') }}
                            </span>

                            <div class="float-right">
                                <a class="btn btn-primary btn-sm" href="{{ route('usuarios.create') }}">Nuevo usuario</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="tabla_usuarios" class="table table-striped table-hover table-bordered table-sm w-100"
                                id="tabla_usuarios" style="white-space: nowrap;">
                                <thead>
                                    <th>ID</th>
                                    <th>Nombre</th>
                                    <th>E-mail</th>
                                    <th>Teléfono</th>
                                    <th>Cédula</th>
                                    <th>Edad</th>
                                    <th>Ciudad</th>
                                    <th>Acciones</th>
                                </thead>
                                <tbody>
                                    @foreach ($usuarios as $usuario)
                                        <tr>
                                            <td>{{ $usuario->id }}</td>
                                            <td>{{ $usuario->name }}</td>
                                            <td>{{ $usuario->email }}</td>
                                            <td>{{ $usuario->telefono }}</td>
                                            <td>{{ $usuario->cedula }}</td>
                                            <td>
                                                @php
                                                    $nacimiento = new DateTime($usuario->fecha_nac);
                                                    $ahora = new DateTime(date('Y-m-d'));
                                                    $diferencia = $ahora->diff($nacimiento);
                                                    echo $diferencia->format('%y');
                                                @endphp
                                            </td>
                                            <td>{{ $usuario->ciudade->ciudade }}</td>
                                            <td>
                                                <a class="btn btn-info btn-sm"
                                                    href="{{ route('usuarios.edit', $usuario->id) }}">Editar</a>

                                                {!! Form::open([
                                                    'method' => 'DELETE',
                                                    'route' => ['usuarios.destroy', $usuario->id],
                                                    'style' => 'display:inline',
                                                    'class' => 'eliminar-usuario',
                                                    'data-id' => $usuario->email,
                                                ]) !!}
                                                {!! Form::submit('Borrar', ['class' => 'btn btn-danger btn-sm']) !!}
                                                {!! Form::close() !!}
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.js"></script>
    <script>
        $(document).ready(function() {
            $('#tabla_usuarios').DataTable();
        });
    </script>
@endsection